### ISSUE TITLE
Redefine getPacketTypeID() functions as macros

### ISSUE THREAD

**Issue by jefffisher** [billvaglienti/ProtoGen#20]
Not sure if it makes any sense to actually implement it, but it'd be nice to be able to do, e.g.:

```
switch (getNovatelPacketID())
{
case getBinaryResponsePacketID():
    // Do something...
    break;
};
```

So in that particular case, it'd be a change in NovatelPackets.h that'd look something like this:

```
- uint32_t getBinaryResponsePacketID(void);
+ #define getBinaryResponsePacketID() (1)
```

**Comment by billvaglienti** [comment]
Done, version 1.4.8.a
