### ISSUE TITLE
Multiple copies of PrococolSupport

### ISSUE THREAD

**Issue by SchrodingersGat** [billvaglienti/ProtoGen#42]
In recent build of protogen, using the `-no-unrecognized-warnings` flag to disable said warnings does not suppress all warnings.

The source of this behaviour is line:129 in *protocoldocumentation.cpp*.

I believe this is occurring because the .support object is being copied to the ProtocolDocumentation class before the .disableunrecognized field is set to *true*.

**Comment by billvaglienti** [comment]
Fixed, I was using the negation of support.disableunrecognized when I should have used the affirmation. This bug was only in 1.9.2.a
