### ISSUE TITLE
ANSI/C89 Compatibility

### ISSUE THREAD

**Issue by jefffisher** [billvaglienti/ProtoGen#7]
Most of the functions generated by fieldencoding.cpp do not compile against ANSI/C89 because they have variable declarations after other statements in the block. For example:

    void stringFromBytes(char* string, const uint8_t* bytes, int* index, int maxLength, int fixedLength)
    {
        // increment byte pointer for starting point
        bytes += *index;
    
        int i;
    
        // [...]
    }

Will not compile because the 'int i' should be before 'bytes += *index':

    void stringFromBytes(char* string, const uint8_t* bytes, int* index, int maxLength, int fixedLength)
    {
        int i;
    
        // increment byte pointer for starting point
        bytes += *index;
    
        // [...]
    }

**Comment by billvaglienti** [comment]
Wow, I can't believe we got this far without finding that error. I'll have
a fix by tomorrow.

Bill Vaglienti
541 399 7883
4207 post canyon
hood river, OR, 97031

**Comment by billvaglienti** [comment]
I am currently pulling and building Protogen from github as part of the build so when you check in a fix it should (cross my fingers) Automagically fix my builds.

Thanks,
Ryan

**Comment by billvaglienti** [comment]
Try it now.

Bill Vaglienti
541 399 7883
4207 Post Canyon
Hood River OR, 97031

**Comment by billvaglienti** [comment]
I am still getting this:

>>>> Optimizer terminated abnormally
>>>>    in function int48FromLeBytes()
>>>>    in file "/var/lib/jenkins/jobs/RetractController/workspace/Public/Communications/fielddecode.c"

>> Compilation failure
gmake: *** [fielddecode.obj] Error 1


Code looks like this:
int64_t int48FromLeBytes(const uint8_t* bytes, int* index)
{
    // A bitfield is a fast portable way to get the compiler to sign extend a non standard size
    // Courtesty of: https://graphics.stanford.edu/~seander/bithacks.html
    struct{int64_t number: 48;}s;

    // increment byte pointer for starting point
    bytes += (*index) + 5;

    s.number = *(bytes--);
    s.number = (s.number << 8) | *(bytes--);
    s.number = (s.number << 8) | *(bytes--);
    s.number = (s.number << 8) | *(bytes--);
    s.number = (s.number << 8) | *(bytes--);
    s.number = (s.number << 8) | *bytes;

    (*index) += 6;

    return s.number;
}

I’ll check it again tomorrow.

Thanks,
Ryan

**Comment by billvaglienti** [comment]
Verified compiles clean with -std=C99, -Wall, -pedantic
