### ISSUE TITLE
Missing packet structure definitions for packets which have initial or verify values

### ISSUE THREAD

**Issue by SchrodingersGat** [billvaglienti/ProtoGen#70]
1. Say you have a packet `MyPacket` which contains the variable `MyStruct`. The packet is set to parameterInterface (but **not** structureInterface).
1. `MyStruct` contains variables that have initialValue or verifyMinValue or verifyMaxValue parameters
1. Due to *structureInterface* not being set, the `MyPacket_t` structure is not defined
1. Protogen will write code to initialize and verify `MyPacket` (due to the inclusion of `MyStruct`)
1. These functions will reference a non-existent `MyPacket_t` struct

I believe that if a packet contains any variables or structures that have initial or verify values, then the packet structure must be also defined, even if structureInterface is set to false.

**Comment by SchrodingersGat** [comment]
Version: 2.11.c

**Comment by SchrodingersGat** [comment]
![image](https://user-images.githubusercontent.com/10080325/34803567-12ed62b8-f6c8-11e7-846e-41685a7d0f47.png)

Here the functions (generated by Protogen) are failing because the structure definition for packet `Servo_SetConfigBits_t` has not been defined anywhere...

**Comment by SchrodingersGat** [comment]
Current workaround is to ensure that `structureInterface` is set to true for affected packets. But this is not ideal.

**Comment by billvaglienti** [comment]
I updated to logic that forces the structure declaration, version 2.11.d. Give that a try. If it doesn't solve it, then send me your protocol.xml file so I can debug more thoroughly.

**Comment by SchrodingersGat** [comment]
That's done the trick! Thanks very  much :)
