### ISSUE TITLE
StructureInterface defaults to "on"

### ISSUE THREAD

**Issue by SchrodingersGat** [billvaglienti/ProtoGen#78]
In a recent update to Protogen (I think the commit on 26th April) encode and decode routines are automatically generated for structure versions of the packets. This is even the case for packets which do not define a structure.

i.e. if you have defined a packet but not set `structureInterface="true"` then the encodeStructure and decodeStructure functions are defined anyway. But the actual structures are not defined so the functions point to structure arguments that don't exist.

I think this is a regression. If the encode/decode functions are defined then the structs they point to must be defined too.

**Comment by billvaglienti** [comment]
I think this was caused by the print, compare, map, init, and verify capabilities. When enabled globally these features would force the creation of the structure functions. Now that logic has been amended to disable those features for cases where the structures are empty
