### ISSUE TITLE
Table Captions Broken With newer Markdown (version 5 and up)

### ISSUE THREAD

**Issue by aaronjaques** [billvaglienti/ProtoGen#87]
Newer multimarkdown (v 5 and up) expects captions for tables to appear after table definitions rather than before (http://fletcher.github.io/MultiMarkdown-5/tables.html). The current markdown created by ProtoGen results in tables that appear as blobs of text in a paragraph in the HTML generated with Multimarkdown.

**Comment by billvaglienti** [comment]
Changed in 2.17
