### ISSUE TITLE
Another error building protogen

### ISSUE THREAD

**Issue by knoll01** [billvaglienti/ProtoGen#97]
I apologize for the build-related questions. I don't know C++ very well. 

After realizing that ProtoGen is a qmake project and needed c++17 support, I was able to get further. Compiling on Ubuntu 18.04 requires installation of gcc 8 and Qt5. I also had to modify ProtoGen.pro to include 

CONFIG += c++1z
QMAKE_CXX = g++-8

Now I can generate the Makefile and the build process fails with:

g++-8 -c -pipe -O2 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -Itinyxml -IprebuiltSources -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o protocolfield.o protocolfield.cpp
protocolfield.cpp: In member function ‘std::__cxx11::string ProtocolField::getNumberString(double, int) const’:
protocolfield.cpp:5008:37: error: ‘FLT_DECIMAL_DIG’ was not declared in this scope
         stream << std::setprecision(FLT_DECIMAL_DIG);
                                     ^~~~~~~~~~~~~~~
protocolfield.cpp:5008:37: note: suggested alternative: ‘DECIMAL_DIG’
         stream << std::setprecision(FLT_DECIMAL_DIG);
                                     ^~~~~~~~~~~~~~~
                                     DECIMAL_DIG
protocolfield.cpp:5010:37: error: ‘DBL_DECIMAL_DIG’ was not declared in this scope
         stream << std::setprecision(DBL_DECIMAL_DIG - 1);
                                     ^~~~~~~~~~~~~~~
protocolfield.cpp:5010:37: note: suggested alternative: ‘DECIMAL_DIG’
         stream << std::setprecision(DBL_DECIMAL_DIG - 1);
                                     ^~~~~~~~~~~~~~~
                                     DECIMAL_DIG
protocolfield.cpp: In static member function ‘static std::__cxx11::string ProtocolField::getDisplayNumberString(double)’:
protocolfield.cpp:5076:37: error: ‘DBL_DECIMAL_DIG’ was not declared in this scope
         stream << std::setprecision(DBL_DECIMAL_DIG - 1);
                                     ^~~~~~~~~~~~~~~
protocolfield.cpp:5076:37: note: suggested alternative: ‘DECIMAL_DIG’
         stream << std::setprecision(DBL_DECIMAL_DIG - 1);
                                     ^~~~~~~~~~~~~~~
                                     DECIMAL_DIG
Makefile:502: recipe for target 'protocolfield.o' failed
make: *** [protocolfield.o] Error 1

A little research indicates that FLT_DECIMAL_DIG is defined in <cfloat> which is not included anywhere in the code. I added #include <cfloat> to protocolfield.h, but that fails with the error. Again, I'm a C++ neophyte, so I'm not sure how to fix this.

I tried compiling with clang 6, also, but can't get past a different set of include errors.

I've had to add #define <algorithm> to protocolsupport.cpp and I get stuck at 

clang++ -c -pipe -O2 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -Itinyxml -IprebuiltSources -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o protocolbitfield.o protocolbitfield.cpp
protocolbitfield.cpp:302:96: error: no member named 'str' in 'std::basic_ostream<char>'
        mask = " & 0x" + toUpper((std::stringstream() << std::hex << maxvalueoffield(numbits)).str());
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
protocolbitfield.cpp:353:112: error: no member named 'str' in 'std::basic_ostream<char>'
        std::string mask = " & 0x" + toUpper((std::stringstream() << std::hex << maxvalueoffield(leadingbits)).str());
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

Thanks for your assistance.

**Comment by billvaglienti** [comment]
The .pro file already had CONFIG += c++17, which is the same as c++1z. I don't know what QMAKE_CXX = g++-8 is supposed to do.

In any case the definitions that are being complained about are in float.h, which is being included in the protocolfield.cpp file on line 9. That file is part of the c standard, so there should be no issue including it. The problem is that float.h from MinGW has these definitions protected by:

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 201112L

Which is not defined in g++. Apparently this is a compiler choice (sigh...)

Both MSVC and Clang compile this code cleanly.

I've re-worked the sections you had errors with. I think GCC should be OK with them now.

**Comment by knoll01** [comment]
Thanks for this fix.  The build completes now with a couple of warnings.

I still need to add
QMAKE_CXX = g++-8
CONFIG += c++1z 

The default g++ on Ubuntu 18.04 is version 7.5 which has incomplete support for #include <filesystem> which causes the build to fail with 
protocolparser.cpp:15:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:467: recipe for target 'protocolparser.o' failed
make: *** [protocolparser.o] Error 1 

This is fixed in g++ version 8.

ProtoGen.pro needs QMAKE_CXX = g++-8 to select g++ version 8 as the compiler.

It turns out that there is also a bug or quirk in g++ version 8 that causes it to not recognize c++17, so ProtoGen.pro needs CONFIG += c++1z as a workaround.

Lastly, I had to add 

LIBS += -L/usr/lib/gcc/x86_64-linux-gnu/8/ -lstdc++fs

which forces the linker to use version 8 of the libstdc++fs instead of the default version 6 on Ubuntu.

Clearly this is all compiler versions and platform dependencies, but it might be helpful for the next person that tries on a default Ubuntu system.
