### ISSUE TITLE
Should Example Protocol build?

### ISSUE THREAD

**Issue by knoll01** [billvaglienti/ProtoGen#98]
Should ProtoGen be able to generate code from exampleprotoco.xml?

./ProtoGen ./exampleprotocol.xml 

ProtoGen version 3.1.e
Parsing file exampleprotocol.xml
Parsing file dependson.xml
Parsing file bitfieldtester.xml
dependson.xml(28): warning: Demolink:testPacket:sync0:testwarning: Unrecognized attribute
Failed to open base_compare.cpp
Failed to open base_compare.hpp
Failed to open base_print.cpp
Failed to open base_print.hpp
Failed to open base_map.cpp
Failed to open base_map.hpp
Failed to open compareDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open printDemolink.cpp
Failed to open printDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open dateverify.h
Failed to open dateverify.c
Failed to open compareDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open printDemolink.cpp
Failed to open printDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open printDemolink.cpp
Failed to open printDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open verify.h
Failed to open verify.c
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open verify.h
Failed to open verify.c
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open verify.h
Failed to open verify.c
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open EngineDefinitions.hpp
Failed to open verify.h
Failed to open verify.c
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open verify.h
Failed to open verify.c
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Failed to open compareDemolink.hpp
Failed to open compareDemolink.cpp
Failed to open printDemolink.hpp
Failed to open printDemolink.cpp
Failed to open mapDemolink.hpp
Failed to open mapDemolink.cpp
Writing HTML documentation to Demolink.html
Generated protocol files in ./
error: failed to open base_map.hpp
error: failed to open base_map.cpp
error: failed to open base_print.hpp
error: failed to open base_print.cpp
error: failed to open base_compare.hpp
error: failed to open base_compare.cpp
error: failed to open mapDemolink.hpp
error: failed to open mapDemolink.cpp
error: failed to open printDemolink.hpp
error: failed to open printDemolink.cpp
error: failed to open compareDemolink.hpp
error: failed to open compareDemolink.cpp
error: failed to open dateverify.h
error: failed to open dateverify.c
error: failed to open mapDemolink.hpp
error: failed to open mapDemolink.cpp
error: failed to open printDemolink.hpp
error: failed to open printDemolink.cpp
error: failed to open compareDemolink.hpp
error: failed to open compareDemolink.cpp
error: failed to open mapDemolink.hpp
error: failed to open mapDemolink.cpp
error: failed to open printDemolink.hpp
error: failed to open printDemolink.cpp
error: failed to open compareDemolink.hpp
error: failed to open compareDemolink.cpp
error: failed to open verify.h
error: failed to open verify.c

**Comment by billvaglienti** [comment]
Yes it should, and it does. I expect your problem has something to do with your filesystem. Note that if you are generating the example protocol then you would typically do ./ProtoGen exampleprotocol.xml ProtoGenTest. In this way you can actually build the test application and verify the output code is correct.

**Comment by knoll01** [comment]
Got it. Using ProtoGenTest as the destination directory fixed this. THanks
