### ISSUE TITLE
Autogenerate getPacketID() function

### ISSUE THREAD

**Issue by knoll01** [billvaglienti/ProtoGen#99]
This might be out of scope for ProtoGen, but I'll put in a request for it anyway...

It would be nice to have ProtoGen automatically generate the get<Protocol>PacketID() function based on the data contained in the protocol XML file. It might only be necessary to add a new tag in the Packet sub-document to indicate which field is the "next protocol" or "next packet ID" field.

**Comment by billvaglienti** [comment]
The construction of the ID can be complex based the actual protocol in question. While we could add information information to make it possible I don't think this is warranted, especially since you still have to hand write remainder of the low level packet functions.
